### check the main server
GET http://localhost:8000/api/v1


### ======= Admin Users ======###
### Post admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName": "Subin",
    "lName": "Basnet",
    "email": "subin@basnet1010101212121212.com",
    "password": "subin",
    "phone": "98098098098",
    "address": "sydney",
    "dob": "2020-12-12"
}